//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keysight.KCE.UISamples.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Keysight.KCE.UISamples.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Sample Device.
        /// </summary>
        internal static string HeaderAddSampleDevice {
            get {
                return ResourceManager.GetString("HeaderAddSampleDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Sample Interface.
        /// </summary>
        internal static string HeaderAddSampleInterface {
            get {
                return ResourceManager.GetString("HeaderAddSampleInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Sample Properties:.
        /// </summary>
        internal static string HeaderConfigSampleProperties {
            get {
                return ResourceManager.GetString("HeaderConfigSampleProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Connection Addresses:.
        /// </summary>
        internal static string HeaderConnectionAddresses {
            get {
                return ResourceManager.GetString("HeaderConnectionAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit settings for Sample Instrument.
        /// </summary>
        internal static string HeaderEditSampleDevice {
            get {
                return ResourceManager.GetString("HeaderEditSampleDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit settings for Sample Interface.
        /// </summary>
        internal static string HeaderEditSampleInterface {
            get {
                return ResourceManager.GetString("HeaderEditSampleInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Address:.
        /// </summary>
        internal static string HeaderSetAddress {
            get {
                return ResourceManager.GetString("HeaderSetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Address:.
        /// </summary>
        internal static string LabelBusAddress {
            get {
                return ResourceManager.GetString("LabelBusAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Addresses:.
        /// </summary>
        internal static string LabelConnectionAddressesReadOnly {
            get {
                return ResourceManager.GetString("LabelConnectionAddressesReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Timeout:.
        /// </summary>
        internal static string LabelConnectionTimeout {
            get {
                return ResourceManager.GetString("LabelConnectionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostname or IP Address:.
        /// </summary>
        internal static string LabelHostNameOrIP {
            get {
                return ResourceManager.GetString("LabelHostNameOrIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical Unit:.
        /// </summary>
        internal static string LabelLogicalUnit {
            get {
                return ResourceManager.GetString("LabelLogicalUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Interface ID:.
        /// </summary>
        internal static string LabelSampleID {
            get {
                return ResourceManager.GetString("LabelSampleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SICL Interface ID:.
        /// </summary>
        internal static string LabelSiclInterfaceID {
            get {
                return ResourceManager.GetString("LabelSiclInterfaceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VISA Interface ID:.
        /// </summary>
        internal static string LabelVisaInterfaceID {
            get {
                return ResourceManager.GetString("LabelVisaInterfaceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument Name:.
        /// </summary>
        internal static string LableInstrumentName {
            get {
                return ResourceManager.GetString("LableInstrumentName", resourceCulture);
            }
        }
    }
}
